version: '3.8'

services:

  mathster-ui:
    container_name: mathster-ui
    build: .
    image: mathster-ui:0.0.1
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true